[package]
name = "pss-app"
version = "0.1.0"
edition = "2024"

[dependencies]
pss-core = { workspace = true }
egui = "0.26"
egui-phosphor = "0.11.0"
egui-wgpu = "0.26"
egui-winit = "0.26"
pixels = "0.15"
strum = { workspace = true }
strum_macros = { workspace = true }
winit = "0.29"